name: Build and Test CI

on:
  push:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        id: tests
        run: npm run coverage

      - name: Build for deployment
        if: steps.tests.outcome == 'success'
        run: |
          npm run build_prod
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add deployment
          git commit -m "Build for deployment"
          git push origin main

      - name: Send coverage data to Coveralls
        run: npx coveralls < ./coverage/lcov.info
